default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: desafioeasy_back_development
  username: hygor1
  password: 481593
  host: localhost
  port: 5432

test:
  <<: *default
  database: desafioeasy_back_test
  username: hygor1
  password: 481593
  host: localhost
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
